---
title: "group3_1"
author: "Michael Im"
date: "February 18, 2017"
output: html_document
---

```{r}

library(dplyr)
library(ggplot2)
library(data.table)

cb <- read.csv("citibike.csv") #CHANGE SO THAT IT FITS THE MERGED FILE

```


```{r}

library(leaflet)

#EXAMPLE CODE

m <- leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng=174.768, lat=-36.852, popup="The birthplace of R")
m  # Print the map

data(quakes)

# Show first 20 rows from the `quakes` dataset
leaflet(data = quakes[1:20,]) %>% addTiles() %>%
  addMarkers(~long, ~lat, popup = ~as.character(mag))

leaflet(quakes) %>% addTiles() %>% addMarkers(
  clusterOptions = markerClusterOptions()
)

```


```{r}

cb_sample <- cb[1:500,]

leaflet(data = cb_sample) %>% addTiles() %>%
  addMarkers(~cb_sample$end.station.longitude, ~cb_sample$start.station.latitude, popup = ~cb_sample$start.station.name, clusterOptions = markerClusterOptions()) %>%   addProviderTiles("CartoDB.Positron")

```