---
title: "Untitled"
author: "Evan Fisher"
date: "February 15, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```





```{r}

temp <- tempfile()
download.file("https://s3.amazonaws.com/tripdata/201601-citibike-tripdata.zip",temp, mode="wb")
unzip(temp, "201601-citibike-tripdata.csv")
data1 <- read.csv("201601-citibike-tripdata.csv")

download.file("https://s3.amazonaws.com/tripdata/201602-citibike-tripdata.zip",temp, mode="wb")
unzip(temp, "201602-citibike-tripdata.csv")
data2 <- read.csv("201602-citibike-tripdata.csv")

download.file("https://s3.amazonaws.com/tripdata/201603-citibike-tripdata.zip",temp, mode="wb")
unzip(temp, "201603-citibike-tripdata.csv")
data3 <- read.csv("201603-citibike-tripdata.csv")

download.file("https://s3.amazonaws.com/tripdata/201604-citibike-tripdata.zip",temp, mode="wb")
unzip(temp, "201604-citibike-tripdata.csv")
data4 <- read.csv("201604-citibike-tripdata.csv")

download.file("https://s3.amazonaws.com/tripdata/201605-citibike-tripdata.zip",temp, mode="wb")
unzip(temp, "201605-citibike-tripdata.csv")
data5 <- read.csv("201605-citibike-tripdata.csv")

download.file("https://s3.amazonaws.com/tripdata/201606-citibike-tripdata.zip",temp, mode="wb")
unzip(temp, "201606-citibike-tripdata.csv")
data6 <- read.csv("201606-citibike-tripdata.csv")

download.file("https://s3.amazonaws.com/tripdata/201607-citibike-tripdata.zip",temp, mode="wb")
unzip(temp, "201607-citibike-tripdata.csv")
data7 <- read.csv("201607-citibike-tripdata.csv")

download.file("https://s3.amazonaws.com/tripdata/201608-citibike-tripdata.zip",temp, mode="wb")
unzip(temp, "201608-citibike-tripdata.csv")
data8 <- read.csv("201608-citibike-tripdata.csv")

download.file("https://s3.amazonaws.com/tripdata/201609-citibike-tripdata.zip",temp, mode="wb")
unzip(temp, "201609-citibike-tripdata.csv")
data9 <- read.csv("201609-citibike-tripdata.csv")

download.file("https://s3.amazonaws.com/tripdata/201610-citibike-tripdata.zip",temp, mode="wb")
unzip(temp, "201610-citibike-tripdata.csv")
data10 <- read.csv("201610-citibike-tripdata.csv")

download.file("https://s3.amazonaws.com/tripdata/201611-citibike-tripdata.zip",temp, mode="wb")
unzip(temp, "201611-citibike-tripdata.csv")
data11 <- read.csv("201611-citibike-tripdata.csv")

download.file("https://s3.amazonaws.com/tripdata/201612-citibike-tripdata.zip",temp, mode="wb")
unzip(temp, "201612-citibike-tripdata.csv")
data12 <- read.csv("201612-citibike-tripdata.csv")


data.all <- merge(data1, data2, all = TRUE)
data.all <- merge(data.all, data3, all = TRUE)
data.all <- merge(data.all, data4, all = TRUE)
data.all <- merge(data.all, data5, all = TRUE)
data.all <- merge(data.all, data6, all = TRUE)
data.all <- merge(data.all, data7, all = TRUE)
data.all <- merge(data.all, data8, all = TRUE)
data.all <- merge(data.all, data9, all = TRUE)
data.all <- merge(data.all, data10, all = TRUE)
data.all <- merge(data.all, data11, all = TRUE)
data.all <- merge(data.all, data12, all = TRUE)


num.rows = nrow(data.all) * 0.005

data.small <- data.all[sample(nrow(data.all), num.rows), ]


```



